"""lesson1/exercises.py

This file contains exercises to demonstrate how to

  1) Run Python code from a file and in the REPL.
  2) Print to the console

"""

# Python processes instructions line-by-line.  Each line tells the
# machine to do something, for example, to print text to the console,
# to add two numbers, to call a function, or to exit.
#
# A simple way to organize a Python program is to put instructions
# in a file, like this one, and tell Python to "execute" the file.
# The workflow is as follows:
#
#   1) Create a file.
#   2) Add instructions to the file.
#   3) Save the file.
#   4) Tell Python to execute the file.
#
# You will be using an IDE, or integrated development environment.
# An IDE has buttons for doing all of the above.
#
# Exercise 0: Open this file in a Python IDE.
#
# This file already has some instructions.  We can execute this
# file to run those instructions.

print("This is a simple Python instruction.")
print("5 + 5 ={}".format(5 + 5))

# Exercise 1: Execute this file.

# As you may have noticed, lines beginning with "#" are comments,
# indicating that they should not be processed as instructions.
#
# The simplest Python command is the print statement. print is a
# function that takes a string of text and prints it to the console.
# The console contains the output of a program.  In Python, this
# output is generated by print statements and by errors.  For now,
# if you see an error, it is probably a programming error, meaning
# that your code is formatted incorrectly.
#
# A string is an object in python that represents text.  Here are
# a few examples:

"I'm a string."

'I\'m also a string.'

"""I'm a
string that
spans multiple
lines.
"""

# You will learn more about strings in lesson 3.

# Exercise 2: Print "Hello world!"
#   * Add a statement in this file to print the string "Hello world!"
#     to the console.
#   * Execute this file to check your code.

print("Hello world!")

# Now, you will create a new file and add some instructions to it.

# Exercise 3: First Python program.
#   * Make a file called hello.py in the same folder as this one.
#   * Add code to print the string "Hello world!" to the console.
#   * Add a comment describing what the program does.
#   * Execute the file.

# We can also run Python commands one-by-one, instead of saving them 
# to files.  This can be useful when testing out small pieces of code.
# We use the REPL (read-evaluate-print loop) for this.
#
# The REPL is exactly as it sounds.  You type in a line of code, the
# REPL reads it, evaluates it as a Python instruction, prints
# the result, and then asks you for another line of code.

# Exercise 4: Open a REPL in your IDE.

# Unlike when running code from a file, the REPL prints every expression
# you type. If you type a string into the REPL, it will print that
# string. If you type an arithmetic expression into the REPL, it will
# evaluate it and print the result.  print statements are unnecessary
# in the REPL.

# Exercise 5: Print "Hello world!" from the REPL.

# Exercise 6: Play around with the IDE, using basic math operators.

# You will learn more about arithmetic in lesson 2.
#
# It's not as easy to save the code typed into the REPL, so we will
# generally only use files.  Sometimes, it may help to paste a line of
# code into the REPL to check that it works.

# Extra exercises:

# Sometimes we will have more complicated programs, where we will
# want to split the code into multiple files.  In this case, each
# file specifies which other files need to be read via the "import"
# keyword.

# Exercise: Large Python program.
#   * Make a file called main.py in this folder.
#   * Add the following line to main.py:
#       import hello
#   * Execute main.py.
#   * Is the result what you would have expected?

# In general we can use import to include definitions of variables,
# functions, and classes from other files, and not to execute print
# statements.  Revisit this after learning about variables, functions,
# and classes, and see if you can make a program that uses definitions
# from other files.

# Instead of using an IDE, we can run code from the UNIX command line.
# If you are running Linux or OS X, open Terminal.  If you are running
# Windows, skip this exercise, or ask an instructor to show you on
# another machine.

# Exercise: Use the command line.
#   * From the command line, navigate to this directory, and create
#     a new file:
#       cd ../python-game-workshop/lesson1
#       touch example.py
#   * Add code to the file.
#       emacs example.py
#       [Add a line of code and press Ctrl-x, Ctrl-s to save and exit.]
#   * Run the file.
#       python example.py
